export const CAR_SHARING_AGREEMENT_VERSION = 'safarcars-car-sharing-v2';

export type AgreementPolicySnapshot = {
  securityDeposit: number;
  includedKilometresPer24Hours: number;
  excessKmRate: number;
  lateGraceMinutes: number;
  lateReturnRatePerHour: number;
  cancellation: {
    moreThan48Hours: string;
    between24And48Hours: string;
    lessThan24Hours: string;
  };
};

export function agreementPolicySnapshot(policy: any): AgreementPolicySnapshot {
  return {
    securityDeposit: Number(policy.securityDeposit || 0),
    includedKilometresPer24Hours: Number(policy.includedKilometresPer24Hours || 0),
    excessKmRate: Number(policy.excessKmRate || 0),
    lateGraceMinutes: Number(policy.lateGraceMinutes || 0),
    lateReturnRatePerHour: Number(policy.lateReturnRatePerHour || 0),
    cancellation: {
      moreThan48Hours: String(policy.cancellation?.moreThan48Hours || ''),
      between24And48Hours: String(policy.cancellation?.between24And48Hours || ''),
      lessThan24Hours: String(policy.cancellation?.lessThan24Hours || ''),
    },
  };
}

/**
 * These are the booking-facing clauses from the supplied Safarcars Car
 * Sharing Agreement. The signed booking record carries the version and the
 * policy values used at creation, so later policy edits cannot rewrite an
 * already accepted booking.
 */
export function carSharingAgreementTerms(policy: AgreementPolicySnapshot): string[] {
  return [
    'This electronic record is generated by Safar and becomes binding when the Parties accept it on the Platform by click, OTP, electronic acknowledgement, or completion of the booking.',
    'The Host leases the Vehicle to the Guest for the stated Booking Period. Safar is the Platform Operator and technology facilitator; it does not own, insure, maintain, or control the Vehicle.',
    'The Guest confirms that the Guest is eligible to drive, has completed required KYC and driving licence verification, and will keep the licence valid for the full Booking Period.',
    'Only the Primary Guest and one Co-Driver who has been verified and approved on the Platform may drive the Vehicle.',
    'The Vehicle may be used only for personal, non-commercial travel in India and in compliance with applicable law, the listing restrictions, the owner manual, and the Vehicle insurance conditions.',
    'Commercial use, sub-rental, racing, stunts, drifting, towing, off-road use, unlawful activity, overloaded use, driving under the influence, unauthorised drivers, and tampering with tracking or safety devices are prohibited.',
    'Ownership and title remain with the registered owner. The Guest must not sell, pledge, mortgage, sub-lease, lend, or create any charge over the Vehicle, its documents, keys, accessories, or devices.',
    'The Host must provide a roadworthy, clean and accurately described Vehicle with valid RC, insurance, PUC, permits and accessories for the full Booking Period.',
    'Handover and return inspections, time-stamped photographs, video, fuel level, odometer readings, existing damage and accessories are part of this Agreement and may be used to settle disputes.',
    `The Booking Fee includes the Included Kilometres shown in Schedule I. Distance above that allowance is reviewed at ₹${policy.excessKmRate}/km using the inspection records and, where available, telematics data.`,
    `A ₹${policy.securityDeposit} refundable Security Deposit is held as security for documented late return, damage, excess distance, fuel, tolls, fines, cleaning, repair costs and other amounts due under this Agreement.`,
    `A ${policy.lateGraceMinutes}-minute late-return grace period applies. After the grace period, late return is reviewed at ₹${policy.lateReturnRatePerHour}/hour, in addition to any approved extension or other applicable charge.`,
    'The Vehicle must be returned at or before the stated Booking End Date and time to the agreed location. An extension is valid only when requested through the Platform, approved, and paid before the original end time.',
    'The Guest must report an accident, theft, breakdown, damage, warning light, or safety issue immediately through the Platform and follow the Host, Safar, police, and insurer instructions.',
    'The Guest is responsible for tolls, FASTag, parking, permits, traffic violations, challans, fuel shortfall, cleaning, and damage or loss caused by breach, negligence, prohibited use, intoxication, or unauthorised use.',
    'Safar may charge Additional Charges to the selected payment method or deduct documented amounts from the Security Deposit. The remaining balance is released after check-out and pending charge review under the settlement process.',
    `Cancellation, no-show and refund amounts follow the policy in force when this booking was confirmed: more than 48 hours — ${policy.cancellation.moreThan48Hours}; 24–48 hours — ${policy.cancellation.between24And48Hours}; less than 24 hours — ${policy.cancellation.lessThan24Hours}`,
    'Safar may suspend or terminate a booking or account for fraud, false KYC, unsafe conduct, non-payment, prohibited use, invalid licence, unauthorised driving, device tampering, or non-return of the Vehicle.',
    'The Parties consent to the use of booking, KYC, payment, inspection, location, telematics, communication and incident data as necessary to perform this Agreement, protect the Vehicle, settle charges, process insurance, and comply with law.',
    'The Parties must first raise booking, damage, deposit, fine, refund and charge disputes through Safar support with the relevant inspection records, photographs, invoices and notices.',
    'The Agreement is governed by the laws of India. The electronic booking record, acknowledgement time, IP/device information, payment record and inspection records are retained as evidence of acceptance and performance.',
  ];
}
